import { SupportedLanguage } from '../i18n/types';
import { WordPuzzleLevel } from './wordPuzzlesData';

export const MULTILINGUAL_LEVELS: Record<SupportedLanguage, WordPuzzleLevel[]> = {
  en: [
    {
      id: 'en-01',
      puzzleNumber: 1,
      title: 'Nature & Landscapes',
      theme: 'Earth & Waters',
      description: 'Find calming words from rivers, forests, and the open sky.',
      gridSize: 10,
      words: ['RIVER', 'MOUNTAIN', 'FOREST', 'OCEAN', 'CLOUD', 'SUN', 'VALLEY', 'RAIN'],
    },
    {
      id: 'en-02',
      puzzleNumber: 2,
      title: 'Fresh Fruits & Garden',
      theme: 'Orchard Harvest',
      description: 'Search for sweet fruits and nourishing garden produce.',
      gridSize: 10,
      words: ['APPLE', 'MANGO', 'ORANGE', 'PAPAYA', 'BANANA', 'BERRY', 'MELON', 'GUAVA'],
    },
    {
      id: 'en-03',
      puzzleNumber: 3,
      title: 'Wonderful Wildlife',
      theme: 'Creatures of the Earth',
      description: 'Spot graceful birds and gentle animals hidden in the grid.',
      gridSize: 10,
      words: ['ELEPHANT', 'HORNBILL', 'TIGER', 'DOLPHIN', 'EAGLE', 'DEER', 'OTTER', 'FALCON'],
    },
    {
      id: 'en-04',
      puzzleNumber: 4,
      title: 'Warm Hearth & Home',
      theme: 'Comfort & Hearth',
      description: 'Find familiar, comforting objects from cozy home life.',
      gridSize: 10,
      words: ['GARDEN', 'HEARTH', 'TEAPOT', 'KITCHEN', 'VERANDA', 'BLANKET', 'LANTERN', 'WINDOW'],
    },
    {
      id: 'en-05',
      puzzleNumber: 5,
      title: 'Natural Wonders',
      theme: 'Wonders of the World',
      description: 'Discover breathtaking formations across mountain and sea.',
      gridSize: 10,
      words: ['AURORA', 'CANYON', 'GLACIER', 'VOLCANO', 'REEF', 'DESERT', 'ISLAND', 'MEADOW'],
    },
    {
      id: 'en-06',
      puzzleNumber: 6,
      title: 'Peaceful Seasons',
      theme: 'Cycles of Time',
      description: 'Cherish the passing rhythms of autumn, spring, and winter mist.',
      gridSize: 10,
      words: ['SPRING', 'SUMMER', 'AUTUMN', 'WINTER', 'BREEZE', 'SUNSHINE', 'BLOSSOM', 'HARVEST'],
    },
  ],
  as: [
    {
      id: 'as-01',
      puzzleNumber: 1,
      title: 'প্ৰকৃতি আৰু দৃশ্যপট',
      theme: 'জল আৰু মাটি',
      description: 'নৈ, পাহাৰ আৰু মুকলি আকাশৰ পৰা শান্ত শব্দ বিচাৰক।',
      gridSize: 10,
      words: ['নদী', 'পাহাৰ', 'অৰণ্য', 'সাগৰ', 'মেঘ', 'সূৰ্য', 'উপত্যকা', 'বৰষুণ'],
    },
    {
      id: 'as-02',
      puzzleNumber: 2,
      title: 'সতেজ ফল আৰু বাৰী',
      theme: 'বাৰীৰ সোৱাদ',
      description: 'মিঠা ফল আৰু পুষ্টিকৰ বাৰীৰ উৎপাদন বিচাৰক।',
      gridSize: 10,
      words: ['আপেল', 'আম', 'কমলা', 'অমিতা', 'কল', 'জামুক', 'তৰমুজ', 'মধুৰি'],
    },
    {
      id: 'as-03',
      puzzleNumber: 3,
      title: 'সুন্দৰ বন্যপ্ৰাণী',
      theme: 'ধৰিত্ৰীৰ জীৱকুল',
      description: 'গ্ৰিডত লুকাই থকা চৰাই আৰু কোমল জন্তুসমূহ চিনাক্ত কৰক।',
      gridSize: 10,
      words: ['হাতী', 'ধনেশ', 'বাঘ', 'শিহু', 'ঈগল', 'হৰিণা', 'উদ', 'বাজ'],
    },
    {
      id: 'as-04',
      puzzleNumber: 4,
      title: 'ঘৰুৱা আনন্দ',
      theme: 'শান্ত পৰিবেশ',
      description: 'ঘৰৰ চিনাকি আৰু সান্ত্বনাদায়ক সামগ্ৰী বিচাৰক।',
      gridSize: 10,
      words: ['বাগান', 'চৌকা', 'কেতলি', 'ৰান্ধনি', 'বাৰাণ্ডা', 'কম্বল', 'চাকি', 'খিৰিকী'],
    },
    {
      id: 'as-05',
      puzzleNumber: 5,
      title: 'প্ৰাকৃতিক বিস্ময়',
      theme: 'ধৰাৰ ৰূপ',
      description: 'পৰ্বত আৰু সাগৰৰ মনোমোহা স্থানসমূহ আৱিষ্কাৰ কৰক।',
      gridSize: 10,
      words: ['ধ্ৰুৱজ্যোতি', 'প্ৰপাত', 'হিমবাহ', 'আগ্নেয়গিৰি', 'প্ৰবাল', 'মৰুভূমি', 'দ্বীপ', 'ঘাহঁনি'],
    },
    {
      id: 'as-06',
      puzzleNumber: 6,
      title: 'শান্ত ঋতুসমূহ',
      theme: 'সময়ৰ ছন্দ',
      description: 'শৰৎ, বসন্ত আৰু শীতৰ কুঁৱলীৰ সুন্দৰ ছন্দ উপভোগ কৰক।',
      gridSize: 10,
      words: ['বসন্ত', 'গ্ৰীষ্ম', 'শৰৎ', 'শীত', 'বতাহ', 'ৰ’দ', 'পুষ্প', 'ফচল'],
    },
  ],
  bn: [
    {
      id: 'bn-01',
      puzzleNumber: 1,
      title: 'প্রকৃতি ও দৃশ্যপট',
      theme: 'জল ও মাটি',
      description: 'নদী, পাহাড় ও খোলা আকাশের শান্ত শব্দ খুঁজুন।',
      gridSize: 10,
      words: ['নদী', 'পাহাড়', 'অরণ্য', 'সাগর', 'মেঘ', 'সূর্য', 'উপত্যকা', 'বৃষ্টি'],
    },
    {
      id: 'bn-02',
      puzzleNumber: 2,
      title: 'তাজা ফল ও বাগান',
      theme: 'বাগান ফসল',
      description: 'মিষ্টি ফল ও বাগানের স্নিগ্ধ সতেজ সামগ্রী খুঁজুন।',
      gridSize: 10,
      words: ['আপেল', 'আম', 'কমলা', 'পেঁপে', 'কলা', 'জাম', 'তরমুজ', 'পেয়ারা'],
    },
    {
      id: 'bn-03',
      puzzleNumber: 3,
      title: 'মনোরম বন্যপ্রাণী',
      theme: 'ধরণীর প্রাণী',
      description: 'গ্রিডে লুকিয়ে থাকা প্রিয় পাখি ও শান্ত প্রাণীদের সন্ধান করুন।',
      gridSize: 10,
      words: ['হাতি', 'ধনেশ', 'বাঘ', 'শুশুক', 'ঈগল', 'হরিণ', 'ভোঁদড়', 'বাজপাখি'],
    },
    {
      id: 'bn-04',
      puzzleNumber: 4,
      title: 'উষ্ণ গৃহকোণ',
      theme: 'শান্তিময় ঘর',
      description: 'ঘরের চেনা ও আরামদায়ক সামগ্রী খুঁজে বের করুন।',
      gridSize: 10,
      words: ['বাগান', 'উনুন', 'কেতলি', 'রান্নাঘর', 'বারান্দা', 'কম্বল', 'প্রদীপ', 'জানালা'],
    },
    {
      id: 'bn-05',
      puzzleNumber: 5,
      title: 'প্রাকৃতিক বিস্ময়',
      theme: 'জগতের শোভা',
      description: 'পর্বত ও সাগরের রূপ আবিষ্কার করুন।',
      gridSize: 10,
      words: ['মেরুজ্যোতি', 'গিরিখাত', 'হিমবাহ', 'আগ্নেয়গিরি', 'প্রবাল', 'মরুভূমি', 'দ্বীপ', 'তৃণভূমি'],
    },
    {
      id: 'bn-06',
      puzzleNumber: 6,
      title: 'শান্ত ঋতুমালা',
      theme: 'সময়ের ছন্দ',
      description: 'শরৎ, বসন্ত ও শীতের স্নিগ্ধ রূপ স্মরণ করুন।',
      gridSize: 10,
      words: ['বসন্ত', 'গ্রীষ্ম', 'শরৎ', 'শীত', 'বাতাস', 'রোদ', 'পুষ্প', 'ফসল'],
    },
  ],
  mni: [
    {
      id: 'mni-01',
      puzzleNumber: 1,
      title: 'মহৌশাগী শক্তম',
      theme: 'ইশিং অমসুং লৈপাক',
      description: 'তুৰেল, চিং অমসুং অর্বাংবা অতোপিয়াগী ৱাহৈ থিবীয়ু।',
      gridSize: 10,
      words: ['তুৰেল', 'চিংজাউ', 'উমং', 'ইপাক', 'লৈচিল', 'নুমিৎ', 'তম্পাক', 'নোংচু'],
    },
    {
      id: 'mni-02',
      puzzleNumber: 2,
      title: 'মহৈ-মরোং',
      theme: 'লৈকোলগী পোত্থোক',
      description: 'থুম্বা মহৈ-মরোংশিং গ্রিদতা থিবীয়ু।',
      gridSize: 10,
      words: ['হৈবাং', 'হৈনৌ', 'কোমল', 'অৱাতম্বী', 'লাফোই', 'হৈজিল', 'হৈথা', 'পুংদোন'],
    },
    {
      id: 'mni-03',
      puzzleNumber: 3,
      title: 'লম্লক্কী জীবশিং',
      theme: 'মহৌশাগী শা-উচেক',
      description: 'গ্রিদ মনুংদা লোৎতুনা লৈবা শা-উচেকশিং থিবীয়ু।',
      gridSize: 10,
      words: ['সামু', 'উচাক', 'কেই', 'ইশিংউচেক', 'উমাং', 'সাজী', 'উদোল', 'খোকপা'],
    },
    {
      id: 'mni-04',
      puzzleNumber: 4,
      title: 'য়ুমগী নুংঙাইবা',
      theme: 'চানবা য়ুমথোং',
      description: 'য়ুমগী পোৎলমশিং থিবীয়ু।',
      gridSize: 10,
      words: ['লৈকোল', 'মৈফম', 'কেতলি', 'চাখুম', 'মংগোল', 'কম্বল', 'থাওমৈ', 'থোংনাও'],
    },
    {
      id: 'mni-05',
      puzzleNumber: 5,
      title: 'মহৌশাগী অঙকবশিং',
      theme: 'তাইবংগী শক্তম',
      description: 'চিং অমসুং সমুজগী নুংঙাইরবা শক্তমশিং খঙবীয়ু।',
      gridSize: 10,
      words: ['নোংথৌ', 'চিংলাক', 'উন্থাক', 'মৈচিং', 'লুথিক', 'মৰুভূমি', 'ইথৎ', 'নাপাক'],
    },
    {
      id: 'mni-06',
      puzzleNumber: 6,
      title: 'ঋতুগী মতম',
      theme: 'মতমগী ঈচেল',
      description: 'বসন্ত, নিংথোল অমসুং কালেনগী মতমশিং।',
      gridSize: 10,
      words: ['য়েন্থা', 'কালেন', 'নাখোং', 'নিংথোল', 'নুংশিৎ', 'নোংজু', 'লৈরাং', 'লৌৰোক'],
    },
  ],
  kha: [
    {
      id: 'kha-01',
      puzzleNumber: 1,
      title: 'Ka Mariang & Jingitynnat',
      theme: 'Ki Um & Khyndew',
      description: 'Wad ki ktien na ki wah, khlaw, bad bneng.',
      gridSize: 10,
      words: ['WAH', 'LUM', 'KHLAW', 'DURIW', 'LYOH', 'SNGI', 'THEI', 'SLAP'],
    },
    {
      id: 'kha-02',
      puzzleNumber: 2,
      title: 'Ki Soh & Kper',
      theme: 'Jingthung Kper',
      description: 'Wad ki soh thiang bad jingbam ba bha.',
      gridSize: 10,
      words: ['SOHTRUN', 'SOHPIENG', 'SOHNIAM', 'SOHKBA', 'KAIT', 'SOHSHAN', 'SOHMYN', 'SOHPRIW'],
    },
    {
      id: 'kha-03',
      puzzleNumber: 3,
      title: 'Mrad & Sim Khlaw',
      theme: 'Ki Jingthaw Mariang',
      description: 'Shem ki sim bad mrad ba don ha ka grid.',
      gridSize: 10,
      words: ['HATHI', 'SIMENG', 'KHLA', 'DOHKHA', 'KHLIK', 'SKIEI', 'KSHIAD', 'NGAB'],
    },
    {
      id: 'kha-04',
      puzzleNumber: 4,
      title: 'Ka Iing Suk',
      theme: 'Dpei & Jingim',
      description: 'Ki tiar iing ba mlien bad kiba jem ban kynmaw.',
      gridSize: 10,
      words: ['KPER', 'DPEI', 'KLIENG', 'SHETTNG', 'BARANDA', 'SYNRAN', 'SHARAK', 'ITKHMAT'],
    },
    {
      id: 'kha-05',
      puzzleNumber: 5,
      title: 'Kiei Kiba phylla',
      theme: 'Jingitynnat Pyrthei',
      description: 'Wad ki jaka ba itynnat jong ki lum bad duriaw.',
      gridSize: 10,
      words: ['SNIEH', 'KHYNDEW', 'THAH', 'DINGLUM', 'MAW', 'RISHYIAP', 'DEWLYN', 'PHLANG'],
    },
    {
      id: 'kha-06',
      puzzleNumber: 6,
      title: 'Ki Aïom ba Suk',
      theme: 'Ka Por ba Lai',
      description: 'Kynmaw ki aïom lyiur, tlang bad pynthei.',
      gridSize: 10,
      words: ['PYNTHEI', 'SHYIAP', 'SAWTEP', 'TYRKHONG', 'LBER', 'POR', 'TIEW', 'OTKBA'],
    },
  ],
  lus: [
    {
      id: 'lus-01',
      puzzleNumber: 1,
      title: 'Leilung & Sik Leh Sa',
      theme: 'Tui leh Ram',
      description: 'Lui, tlang leh van boruak thu zawnna.',
      gridSize: 10,
      words: ['LUI', 'TLANG', 'RAMHMUL', 'TUIPUI', 'CHHUM', 'NI', 'RUAM', 'RUAH'],
    },
    {
      id: 'lus-02',
      puzzleNumber: 2,
      title: 'Thei & Huan Thlai',
      theme: 'Huan Chhuak',
      description: 'Thei thlum leh thlai hring thute zawng rawh.',
      gridSize: 10,
      words: ['THEIHAIT', 'THEIHAI', 'SERTHLUM', 'MAIKAWNG', 'BANANA', 'THEIBAL', 'HMAI', 'KAWLTHEI'],
    },
    {
      id: 'lus-03',
      puzzleNumber: 3,
      title: 'Ram Nungcha Mawi',
      theme: 'Leilung Nungcha',
      description: 'Sava mawi leh ramsa zawn chhuah turte.',
      gridSize: 10,
      words: ['SAI', 'VAKUL', 'SAKEI', 'SANGHA', 'MU', 'SAKHI', 'SAHRAM', 'VALENG'],
    },
    {
      id: 'lus-04',
      puzzleNumber: 4,
      title: 'Inlum & Hahdamna',
      theme: 'In chhung nun',
      description: 'In chhung hmanraw hriatlar leh hlu takte.',
      gridSize: 10,
      words: ['HUAN', 'THAPUI', 'THINGPUI', 'CHHRAW', 'VERANDA', 'PUAN', 'KHAWNVAR', 'TUKVERH'],
    },
    {
      id: 'lus-05',
      puzzleNumber: 5,
      title: 'Khawvel Thilmak',
      theme: 'Leilung Mawi',
      description: 'Tlang sang leh tuipui mawi thute zawng rawh.',
      gridSize: 10,
      words: ['ENGMAWI', 'KUAHAWI', 'VURTLANG', 'MEITLANG', 'LUNGMAWI', 'THALER', 'THLIAR', 'PHAIPHENG'],
    },
    {
      id: 'lus-06',
      puzzleNumber: 6,
      title: 'Sik Leh Sa Rual',
      theme: 'Hunbi Mawi',
      description: 'Ṭhal, nipui leh favang hun thute.',
      gridSize: 10,
      words: ['THAL', 'NIPUI', 'FAKUN', 'THALAI', 'THLIFIM', 'NISA', 'PARMAWI', 'BUHLAWH'],
    },
  ],
  brx: [
    {
      id: 'brx-01',
      puzzleNumber: 1,
      title: 'मिथिंग आरो नुथाय',
      theme: 'दै आरो हा',
      description: 'दैमा, हाजो आरो अखाफोरनि सोदोब नागिर।',
      gridSize: 10,
      words: ['दैमा', 'हाजो', 'हाग्रा', 'सागोर', 'जोमदै', 'सान', 'हायना', 'अखा'],
    },
    {
      id: 'brx-02',
      puzzleNumber: 2,
      title: 'गोदान फिथाय आरो बारि',
      theme: 'बारिनि फिथाय',
      description: 'गोदै फिथायफोरखौ ग्रिदआव नागिर।',
      gridSize: 10,
      words: ['आफेल', 'थाैसो', 'खमफ्ला', 'मुदै', 'थालिर', 'दामफ्ला', 'खारमुज', 'गोयवा'],
    },
    {
      id: 'brx-03',
      puzzleNumber: 3,
      title: 'मोजां जुनावफोर',
      theme: 'बुहुमनि जुनाव',
      description: 'दाउस्रि आरो मोजां जिउआरिफोरखौ नागिर।',
      gridSize: 10,
      words: ['मावजि', 'दाउस्रि', 'मोसा', 'नामानसि', 'दाउखा', 'मोस्रि', 'उद', 'दाउबिला'],
    },
    {
      id: 'brx-04',
      puzzleNumber: 4,
      title: 'न’ख’र आरो गोजोन',
      theme: 'न’नि मुवा',
      description: 'न’नि सिनायथि मुवाफोरखौ नागिर।',
      gridSize: 10,
      words: ['बारि', 'अरंखा', 'केतलि', 'संखं', 'बरान्डा', 'खम्बोल', 'स्रां', 'खिरकि'],
    },
    {
      id: 'brx-05',
      puzzleNumber: 5,
      title: 'मिथिंगायारि सोमोनांथाव',
      theme: 'बुहुमनि महर',
      description: 'हाजो आरो सागोरनि मोजां जायगाफोर।',
      gridSize: 10,
      words: ['स्रांस्रि', 'हाजोखाग', 'थिसुं', 'अरहाजो', 'रोखा', 'बालिहा', 'दिफ', 'गांसेहा'],
    },
    {
      id: 'brx-06',
      puzzleNumber: 6,
      title: 'गोजोन बोथोरफोर',
      theme: 'समनि थांखि',
      description: 'बोसोन्त, दुंथार आरो गोजां बोथोर।',
      gridSize: 10,
      words: ['बोसोन्त', 'दुंथार', 'सिरिबो', 'गोजां', 'बारफि', 'सानफ्लां', 'बारफ्ला', 'फसल'],
    },
  ],
  ne: [
    {
      id: 'ne-01',
      puzzleNumber: 1,
      title: 'प्रकृति र दृश्य',
      theme: 'जल र जमिन',
      description: 'नदी, पहाड र खुला आकाशका शान्त शब्द खोज्नुहोस्।',
      gridSize: 10,
      words: ['नदी', 'पहाड', 'जंगल', 'सागर', 'बादल', 'घाम', 'उपत्यका', 'वर्षा'],
    },
    {
      id: 'ne-02',
      puzzleNumber: 2,
      title: 'ताजा फल र बगैंचा',
      theme: 'बगैंचाको स्वाद',
      description: 'मीठा फलफूल र बगैंचाका उत्पादन खोज्नुहोस्।',
      gridSize: 10,
      words: ['स्याउ', 'आप', 'सुन्तला', 'मेवा', 'केरा', 'जामुन', 'खर्बुजा', 'अम्बा'],
    },
    {
      id: 'ne-03',
      puzzleNumber: 3,
      title: 'सुन्दर वन्यजन्तु',
      theme: 'धर्तीका जीव',
      description: 'ग्रिडमा लुकेका चराचुरुङ्गी र जनावरहरू पत्ता लगाउनुहोस्।',
      gridSize: 10,
      words: ['हात्ती', 'धनेश', 'बाघ', 'डोल्फिन', 'चील', 'मृग', 'ओत', 'बाज'],
    },
    {
      id: 'ne-04',
      puzzleNumber: 4,
      title: 'न्यानो घर र चुल्हो',
      theme: 'शान्त घर',
      description: 'घरका परिचित र आरामदायी वस्तुहरू खोज्नुहोस्।',
      gridSize: 10,
      words: ['बगैंचा', 'चुल्हो', 'केतली', 'भान्सा', 'बरन्डा', 'कम्बल', 'बत्ती', 'झ्याल'],
    },
    {
      id: 'ne-05',
      puzzleNumber: 5,
      title: 'प्राकृतिक आश्चर्य',
      theme: 'संसारको रूप',
      description: 'पहाड र समुद्रका रमणीय ठाउँहरू पत्ता लगाउनुहोस्।',
      gridSize: 10,
      words: ['उत्तरीज्योति', 'खोच', 'हिमनदी', 'ज्वालामुखी', 'मुगा', 'मरुभूमि', 'टापु', 'चौर'],
    },
    {
      id: 'ne-06',
      puzzleNumber: 6,
      title: 'शान्त ऋतुहरू',
      theme: 'समयको लय',
      description: 'वसन्त, वर्षा र हिउँदका सुन्दर लय सम्झनुहोस्।',
      gridSize: 10,
      words: ['वसन्त', 'ग्रीष्म', 'शरद', 'हिउँद', 'हावा', 'शीत', 'फूल', 'बाली'],
    },
  ],
  grt: [
    {
      id: 'grt-01',
      puzzleNumber: 1,
      title: 'A·gilsak & Mariang',
      theme: 'Chi & A·a',
      description: 'Chibil, a·bri aro salgi kattarangko am·bo.',
      gridSize: 10,
      words: ['CHIBIL', 'ABRI', 'BURUNG', 'SAGAL', 'ARAMU', 'SAL', 'CHIDIM', 'MIKKA'],
    },
    {
      id: 'grt-02',
      puzzleNumber: 2,
      title: 'Tegatchu & Bagan',
      theme: 'Bagan Thilthei',
      description: 'Chi·gipa te·bite kattarangko am·bo.',
      gridSize: 10,
      words: ['TEGATSU', 'TEBRONG', 'CHOMBI', 'MODIPHAL', 'KOL', 'BOLTHEI', 'TARBOJ', 'KOMILA'],
    },
    {
      id: 'grt-03',
      puzzleNumber: 3,
      title: 'Matburing & Do·o',
      theme: 'Salantini Matburing',
      description: 'Do·orang aro matburing kattarang.',
      gridSize: 10,
      words: ['MONGMA', 'DOBI', 'MATCHA', 'NATOK', 'DOENG', 'MATCHOK', 'MATBI', 'DOBIBA'],
    },
    {
      id: 'grt-04',
      puzzleNumber: 4,
      title: 'Nokchhung Ka·dongani',
      theme: 'Nokni Tiar',
      description: 'Nokni jakkalgimin kattarangko am·bo.',
      gridSize: 10,
      words: ['BAGAN', 'WALKU', 'KETLI', 'CHAWGARA', 'BERANDA', 'LEP', 'CHAKI', 'KELKI'],
    },
    {
      id: 'grt-05',
      puzzleNumber: 5,
      title: 'A·bri & Chibil A·song',
      theme: 'A·song Mawi',
      description: 'A·gilsakni mawi biaprang.',
      gridSize: 10,
      words: ['CHIRING', 'ABRIRO', 'BOROP', 'WAKUM', 'CHISAGAL', 'CHANGSROK', 'CHIDWIP', 'SAMPHLANG'],
    },
    {
      id: 'grt-06',
      puzzleNumber: 6,
      title: 'Kari Somoy',
      theme: 'Bilsini Somoy',
      description: 'Basanto, saldim aro sin·a somoy.',
      gridSize: 10,
      words: ['BASANTO', 'SALDIM', 'AONAL', 'CHIKCHIK', 'BALWA', 'SALENG', 'BIBAL', 'MIGEP'],
    },
  ],
};

export function getLevelsForLanguage(language: SupportedLanguage): WordPuzzleLevel[] {
  return MULTILINGUAL_LEVELS[language] || MULTILINGUAL_LEVELS.en;
}

export function getPuzzleLevel(language: SupportedLanguage, index: number): WordPuzzleLevel {
  const levels = getLevelsForLanguage(language);
  const safeIndex = Math.abs(index) % levels.length;
  return levels[safeIndex];
}
