import { CaregiverMemory } from './types';

export const SAMPLE_MEMORIES: CaregiverMemory[] = [
  {
    id: 'mem-aita-jorhat',
    name: 'Aita (Grandmother) on the Veranda',
    relationshipOrCategory: 'Family',
    description: 'Aita sitting comfortably on the cane armchair in Jorhat, weaving traditional eri silk and sharing stories with grandchildren.',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Elderly Indian grandmother with warm smile sitting in daylight',
    language: 'Assamese',
    voiceAuthor: 'Granddaughter Ananya (Recorded)',
    audioNoteText: 'Aita, kela kela kotha monot pore ne? Ami xokolue aji apunar usorot asu.',
    isSample: true,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'mem-brahmaputra-boat',
    name: 'Ferry Crossing to Majuli Island',
    relationshipOrCategory: 'Hometown',
    description: 'The gentle river breeze on the wooden ferry crossing from Nimati Ghat, watching river dolphins and water lilies in the sunset.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Scenic tranquil river with misty banks and calm waters',
    language: 'Assamese & English',
    voiceAuthor: 'Son Deep (Recorded)',
    audioNoteText: 'Monot pore ne Deuta, Majulir xotrot ami Bhaona saboloi jua bosa?',
    isSample: true,
    createdAt: '2026-09-02T11:30:00Z',
  },
  {
    id: 'mem-bihu-pitha',
    name: 'Making Til Pitha for Magh Bihu',
    relationshipOrCategory: 'Festivals',
    description: 'The kitchen filled with the aroma of roasted black sesame, jaggery, and fragrant bora rice rolled over the hot cast-iron pan.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Traditional festive treats and fresh ingredients in warm kitchen',
    language: 'Assamese',
    voiceAuthor: 'Daughter-in-law Ritu (Recorded)',
    audioNoteText: 'Aaita, apuni xikua niorot ajiu pitha bhal hoi.',
    isSample: true,
    createdAt: '2026-09-03T15:20:00Z',
  },
  {
    id: 'mem-shillong-pine',
    name: 'Morning Walks in Pine Groves of Shillong',
    relationshipOrCategory: 'Childhood',
    description: 'Walking beneath tall pine trees with cool mountain mist, stopping by the bakery for warm tea and cinnamon buns.',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Peaceful pine forest path bathed in soft morning light',
    language: 'Khasi & English',
    voiceAuthor: 'Grandson Brian (Recorded)',
    audioNoteText: 'Remember the sweet pine needle smell along the Polo grounds road?',
    isSample: true,
    createdAt: '2026-09-04T09:15:00Z',
  },
  {
    id: 'mem-loktak-lake',
    name: 'Boating on Loktak Lake with Family',
    relationshipOrCategory: 'Nature',
    description: 'Floating peacefully past the green circular phumdis under clear blue skies in Manipur, enjoying fresh tea in earthenware cups.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    imageAlt: 'Serene mountain lake with clear reflections and green shores',
    language: 'Meitei & English',
    voiceAuthor: 'Daughter Sanatombi (Recorded)',
    audioNoteText: 'Loktak patta hi tongba matamdu yengbiyu, kayada ningthibano.',
    isSample: true,
    createdAt: '2026-09-05T14:45:00Z',
  },
];
