import type { LucideIcon } from "lucide-react"
import {
  Mountain,
  MountainSnow,
  TreePine,
  Trees,
  Bird,
  Fish,
  Leaf,
  Flower,
  Flower2,
  Sprout,
  House,
  TentTree,
  Utensils,
  UtensilsCrossed,
  Palette,
  Music,
  Drum,
  Shirt,
  Gift,
  Heart,
  Star,
  Coffee,
  Bike,
  Waves,
  Sun,
  Cloud,
  Droplet,
  Droplets,
  Bug,
  Egg,
  Wheat,
  Citrus,
  Soup,
  FishSymbol,
  Footprints,
  HandHeart,
  Smile,
  Feather,
  Grape,
  Banana,
  Carrot,
  Apple,
  CupSoda,
  Church,
  Landmark,
  Castle,
  MapPin,
  Ship,
  Anchor,
  Sailboat,
  Guitar,
  Users,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "tree-pine": TreePine,
  trees: Trees,
  bird: Bird,
  fish: Fish,
  leaf: Leaf,
  flower: Flower,
  "flower-2": Flower2,
  sprout: Sprout,
  house: House,
  "tent-tree": TentTree,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  palette: Palette,
  music: Music,
  drum: Drum,
  shirt: Shirt,
  gift: Gift,
  heart: Heart,
  star: Star,
  coffee: Coffee,
  bike: Bike,
  waves: Waves,
  sun: Sun,
  cloud: Cloud,
  droplet: Droplet,
  droplets: Droplets,
  bug: Bug,
  egg: Egg,
  wheat: Wheat,
  citrus: Citrus,
  soup: Soup,
  "fish-symbol": FishSymbol,
  footprints: Footprints,
  "hand-heart": HandHeart,
  smile: Smile,
  feather: Feather,
  grape: Grape,
  banana: Banana,
  carrot: Carrot,
  apple: Apple,
  "cup-soda": CupSoda,
  church: Church,
  landmark: Landmark,
  castle: Castle,
  "map-pin": MapPin,
  ship: Ship,
  anchor: Anchor,
  sailboat: Sailboat,
  guitar: Guitar,
  users: Users,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Star
}
